version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./api:/app
    ports:
      - 8080:8080
    env_file:
      - ./api/.env.dev
  batch:
    build:
      context: ./batch
    volumes:
      - ./batch:/app
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
