FROM hayd/alpine-deno:1.7.2

EXPOSE 8080

WORKDIR /app

ADD . .
RUN deno cache mod.ts --import-map=import_map.json --unstable

RUN deno install -qAf --unstable https://deno.land/x/denon/denon.ts
CMD ["denon", "start"]