FROM hayd/alpine-deno:1.7.2

EXPOSE 8080

WORKDIR /app

COPY deps.ts .
RUN deno cache deps.ts

ADD . .
RUN deno cache app.ts

RUN deno install -qAf --unstable https://deno.land/x/denon/denon.ts
CMD ["denon", "start"]
